# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Custom-App' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Custom-App

pod 'Firebase/Core'
pod 'FirebaseAuth'
pod 'FirebaseStorage'
pod 'SDWebImage'
pod 'MBProgressHUD'
pod 'SDWebImage'
pod 'FirebaseDatabase'
  
  target 'Custom-AppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Custom-AppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
